### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sharkster91** [sharkster91/SMUI#5]
- [x] Add new zones
- [x] Add new zones to zombie zone definitions
- [x] Add ALICE rig & add it to outfits
- [x] Continue tweaking ALICE rig
- [x] Adding hair style definitions to the new outfits
- [x] New Icons
- [x] Adjust Patrol Caps
- [x] Add Urban Patrol Cap
- [ ] Adjust/Redo Workshop page

* MAYBE *
- [ ] Fashion Montage Support

**Comment by RobertMolders** [comment]
If feasible should be absolutely great adding to the SMUI mod the option to exclude equipment made/built after 1993 ( Like in the Brita's weapons mod to give the idea ).
In particular about the night vision goggles ( basically everything after the AN PVS-5 is non 1993 ). Thanks in advance and best regards.
